from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from psycopg.rows import dict_row
from psycopg import sql
from psycopg import Connection
from .connection import get_pool

from typing import Any

# classes


class EpisodeStatus(str, Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    DONE = "done"
    FAILED = "failed"


@dataclass
class NewEpisode:
    title: str
    batch_id: str | None = None
    podcast_id: str | None = None
    audio_path: str | None = None
    xml_path: str | None = None
    published_at: datetime | None = None


@dataclass
class Episode:
    """
    Output Type
    """

    id: str  # generated by db
    batch_id: str
    title: str
    status: EpisodeStatus
    ingested_at: datetime  # generated by db
    updated_at: datetime
    podcast_id: str | None = None
    audio_path: str | None = None
    xml_path: str | None = None
    transcript_path: str | None = None
    published_at: datetime | None = None


ALLOWED_UPDATE_FIELDS = {
    "title",
    "batch_id",
    "podcast_id",
    "audio_path",
    "xml_path",
    "transcript_path",
    "published_at",
    "status",
    "updated_at",
}

# helpers


def _row_to_episode(row: dict[str, Any]) -> Episode:
    return Episode(
        id=str(row["id"]),
        batch_id=str(row["batch_id"]),
        title=row["title"],
        status=EpisodeStatus(row["status"]),
        ingested_at=row["ingested_at"],
        updated_at=row["updated_at"],
        podcast_id=row.get("podcast_id"),
        audio_path=row.get("audio_path"),
        xml_path=row.get("xml_path"),
        transcript_path=row.get("transcript_path"),
        published_at=row.get("published_at"),
    )


def get(episode_id: str, conn: Connection | None = None) -> Episode | None:
    if conn:
        return _execute_get(episode_id, conn)
    with get_pool().connection() as c:
        return _execute_get(episode_id, c)


def _execute_get(episode_id: str, conn: Connection) -> Episode | None:
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute("SELECT * FROM episodes WHERE id = %s", (episode_id,))
        row = cur.fetchone()
        return _row_to_episode(row) if row else None


def save(episode: NewEpisode, conn: Connection | None = None) -> str:
    if conn:
        return _execute_save(episode, conn)
    with get_pool().connection() as c:
        return _execute_save(episode, c)


def _execute_save(episode: NewEpisode, conn: Connection) -> str:
    """
    Saves a NewEpisode instance to the DB
    return: episode id
    """
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO episodes (title, batch_id, podcast_id, audio_path, xml_path, published_at)
            VALUES (%s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (
                episode.title,
                episode.batch_id,
                episode.podcast_id,
                episode.audio_path,
                episode.xml_path,
                episode.published_at,
            ),
        )
        row = cur.fetchone()
        if not row:
            raise RuntimeError("INSERT returned no id")
        return str(row[0])


def update(
    episode_id: str, fields: dict[str, Any], conn: Connection | None = None
) -> None:
    if conn:
        return _execute_update(episode_id, fields, conn)
    with get_pool().connection() as c:
        return _execute_update(episode_id, fields, c)


def _execute_update(episode_id: str, fields: dict[str, Any], conn: Connection) -> None:
    if not fields:
        return

    invalid = fields.keys() - ALLOWED_UPDATE_FIELDS
    if invalid:
        raise ValueError(f"Invalid update fields: {invalid}")

    assignments = sql.SQL(", ").join(
        sql.SQL("{} = %s").format(sql.Identifier(key)) for key in fields
    )

    query = sql.SQL("UPDATE episodes SET {} WHERE id = %s").format(assignments)
    values = list(fields.values()) + [episode_id]

    with conn.cursor() as cur:
        cur.execute(query, values)


def get_list(
    podcast_id: str | None = None,
    status: EpisodeStatus | None = None,
    batch_id: str | None = None,
    limit: int = 20,
    offset: int = 0,
    conn: Connection | None = None,
) -> list[Episode]:
    if conn:
        return _execute_get_list(conn, podcast_id, status, batch_id, limit, offset)
    with get_pool().connection() as c:
        return _execute_get_list(c, podcast_id, status, batch_id, limit, offset)


def _execute_get_list(
    conn: Connection,
    podcast_id: str | None = None,
    status: EpisodeStatus | None = None,
    batch_id: str | None = None,
    limit: int = 20,
    offset: int = 0,
) -> list[Episode]:
    conditions = []
    values: list[Any] = []

    if podcast_id is not None:
        conditions.append("podcast_id = %s")
        values.append(podcast_id)

    if status is not None:
        conditions.append("status = %s")
        values.append(status.value)

    if batch_id is not None:
        conditions.append("batch_id = %s")
        values.append(batch_id)

    where = f"WHERE {' AND '.join(conditions)}" if conditions else ""
    values += [limit, offset]

    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            sql.SQL(
                "SELECT * FROM episodes {} ORDER BY ingested_at DESC LIMIT %s OFFSET %s"
            ).format(
                sql.SQL(where),
            ),
            values,
        )
        return [_row_to_episode(row) for row in cur.fetchall()]
