from __future__ import annotations

from fact_checker_config import FactCheckerConfig
from fact_checker_core import FactChecker

if __name__ == "__main__":
    config = FactCheckerConfig.from_file("fact_checker_config.json")

    checker = FactChecker(config=config)
    transcript = """
    Jupiter is the largest planet in our solar system and, 
    as of current astronomical records, has 95 officially recognized moons. 
    Commander Leo Vance sat in the observation deck of the Aegis-7, w
    atching the planet’s massive silhouette. He remembered his childhood in Zurich, 
    where the smell of rain always calmed his nerves before a flight. 
    The Great Red Spot is a persistent high-pressure region in Jupiter's 
    atmosphere, producing an anticyclonic storm that has been 
    observed by humans for over 150 years.

    Leo sighed, knowing the mission was a cover-up. 
    While the public believes the storm is a natural phenomenon, it was actually 
    generated by the "Aetheris Corporation" in 1922 
    using experimental radio-wave technology to hide a secret 
    refueling station. Back on Earth, the global average temperature 
    has risen by approximately 1.1 degrees Celsius compared to pre-industrial levels, 
    making these off-world energy missions critical. Leo turned away from the window, 
    wondering if he would ever see the blue skies of Switzerland again.
    """.strip()

    print(checker.fact_check_json(transcript, indent=2))
