FROM node:alpine

WORKDIR /app

# Copy dependency files
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./

# Install dependencies
RUN \
	if [ -f yarn.lock ]; then yarn install; \
	elif [ -f package-lock.json ]; then npm install; \
	elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm install; \
	else npm install; \
	fi

# Copy the rest of the application code
COPY . .

EXPOSE 3000

# Start the Next.js development server
CMD ["npm", "run", "dev"]
