// @title           Media-Lens API
// @version         1.0
// @description     Social Listening tool for podcasts and media.
// @host            localhost:8080
// @BasePath        /api/v1
package main

import (
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"media-lens/backend/internal/api/handlers"
	_ "media-lens/backend/docs" // This will be generated by swag
)

func main() {
	r := gin.Default()

	// API v1 group
	v1 := r.Group("/api/v1")
	{
		v1.GET("/health", HealthCheck)
		
		// Podcasts
		v1.GET("/podcasts", handlers.ListPodcasts)
		v1.POST("/podcasts", handlers.AddPodcast)
		
		// Search
		v1.GET("/search", handlers.SearchTranscripts)
	}

	// Swagger UI route
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.Run(":8080")
}

// HealthCheck godoc
// @Summary      Health check
// @Description  Get the health status of the API
// @Tags         health
// @Produce      json
// @Success      200  {object}  map[string]string
// @Router       /health [get]
func HealthCheck(c *gin.Context) {
	c.JSON(200, gin.H{
		"status": "UP",
	})
}
