// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/audio-url/{id}": {
            "get": {
                "description": "Generate a presigned MinIO URL for streaming an episode's audio file.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audio"
                ],
                "summary": "Get a presigned audio URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Episode ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.AudioURLResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/episodes": {
            "get": {
                "description": "Get episodes, optionally filtered by podcast_id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "episodes"
                ],
                "summary": "List episodes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by podcast ID",
                        "name": "podcast_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Episode"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/episodes/{id}": {
            "get": {
                "description": "Retrieve an episode and all its podcast sections by episode ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "episodes"
                ],
                "summary": "Get a single episode with its sections",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Episode ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.EpisodeWithSections"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/episodes/{id}/sections": {
            "get": {
                "description": "Retrieve all podcast sections for a given episode ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sections"
                ],
                "summary": "Get sections for an episode",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Episode ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.PodcastSection"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Get the health status of the API, including database and MinIO connectivity.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.HealthStatus"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/model.HealthStatus"
                        }
                    }
                }
            }
        },
        "/podcasts": {
            "get": {
                "description": "Get a list of distinct podcasts with episode counts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "podcasts"
                ],
                "summary": "List all podcasts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.PodcastSummary"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "description": "Search all podcast sections for a keyword or phrase using ILIKE.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search through section text",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Max results (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.SearchResult"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AudioURLResponse": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "type": "string",
                    "example": "1h"
                },
                "url": {
                    "type": "string",
                    "example": "https://minio:9000/bronze/audio/...?X-Amz-Signature=..."
                }
            }
        },
        "model.Episode": {
            "type": "object",
            "properties": {
                "audio_path": {
                    "type": "string",
                    "example": "bronze/audio/abc/def/original.mp3"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "ingested_at": {
                    "type": "string"
                },
                "podcast_id": {
                    "type": "string",
                    "example": "the-daily"
                },
                "published_at": {
                    "type": "string",
                    "example": "2026-04-07T00:00:00Z"
                },
                "title": {
                    "type": "string",
                    "example": "The Daily - Monday, April 7"
                },
                "xml_path": {
                    "type": "string",
                    "example": "bronze/podcasts/ep123.xml"
                }
            }
        },
        "model.EpisodeWithSections": {
            "type": "object",
            "properties": {
                "episode": {
                    "$ref": "#/definitions/model.Episode"
                },
                "sections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PodcastSection"
                    }
                }
            }
        },
        "model.HealthStatus": {
            "type": "object",
            "properties": {
                "database": {
                    "type": "string",
                    "example": "UP"
                },
                "minio": {
                    "type": "string",
                    "example": "UP"
                },
                "status": {
                    "type": "string",
                    "example": "UP"
                }
            }
        },
        "model.PodcastSection": {
            "type": "object",
            "properties": {
                "episode_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "id": {
                    "type": "string",
                    "example": "660e8400-e29b-41d4-a716-446655440000"
                },
                "processed_at": {
                    "type": "string"
                },
                "section_idx": {
                    "type": "integer",
                    "example": 1
                },
                "sentiment": {
                    "type": "string",
                    "example": "neutral"
                },
                "sentiment_score": {
                    "type": "number",
                    "example": 0.5
                },
                "text": {
                    "type": "string",
                    "example": "Today we discuss..."
                },
                "topics": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "unknown"
                    ]
                }
            }
        },
        "model.PodcastSummary": {
            "type": "object",
            "properties": {
                "episode_count": {
                    "type": "integer",
                    "example": 42
                },
                "latest_episode": {
                    "type": "string"
                },
                "podcast_id": {
                    "type": "string",
                    "example": "the-daily"
                }
            }
        },
        "model.SearchResult": {
            "type": "object",
            "properties": {
                "episode_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "episode_title": {
                    "type": "string",
                    "example": "The Daily - Monday, April 7"
                },
                "score": {
                    "type": "number",
                    "example": 0.95
                },
                "section_idx": {
                    "type": "integer",
                    "example": 2
                },
                "sentiment": {
                    "type": "string",
                    "example": "neutral"
                },
                "snippet": {
                    "type": "string",
                    "example": "...match found in the transcript..."
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Media-Lens API",
	Description:      "Social Listening tool for podcasts and media.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
